title: Project GitHub Pages
author: Lluis Hernandez
email: 
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Testing how GitHub Pages works

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  lluisher

show_excerpts: true # set to false to remove excerpts on the homepage
